---
- name: Server maintenance, Docker installation, and hardening
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    # System updates
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Update all packages on Debian/Ubuntu
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_os_family == 'Debian'

    # Docker installation
    - name: Install required packages for Docker (Debian/Ubuntu)
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG key (Debian/Ubuntu)
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository (Debian/Ubuntu)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker packages (Debian/Ubuntu)
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    # Basic hardening tasks
    - name: Ensure SSH protocol is set to 2
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Protocol'
        line: 'Protocol 2'
        state: present
      notify: Restart SSH

    - name: Disable root SSH login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify: Restart SSH

    - name: Set strong permissions on /etc/ssh/sshd_config
      ansible.builtin.file:
        path: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'

    - name: Install fail2ban for SSH protection
      ansible.builtin.package:
        name: fail2ban
        state: present

    - name: Enable and start fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        state: started
        enabled: true

    # Cleanup tasks
    - name: Remove unused dependencies (Debian/Ubuntu)
      ansible.builtin.apt:
        autoremove: true
      when: ansible_os_family == 'Debian'

    - name: Clean apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        autoclean: true
      when: ansible_os_family == 'Debian'

    - name: Check if Docker is running
      ansible.builtin.command:
        cmd: docker info
      register: docker_info
      changed_when: false
      failed_when: false

    - name: Clean Docker system
      ansible.builtin.command:
        cmd: docker system prune -af --volumes
      register: docker_prune
      when: docker_info.rc == 0
      changed_when: docker_prune.stdout is search('Total reclaimed space')
      failed_when:
        - docker_prune.rc != 0
        - docker_prune.stderr | default('') != ''
        - not (docker_prune.stderr is search('Error response from daemon') or docker_prune.stderr is search('Cannot connect to the Docker daemon'))

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
